# Deployment for randomizer service for starting up the randomizer
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer
spec:
  replicas: 6
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: randomizer
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
      - image: akaliutau/randomizer:1.0
        name: randomizer
        env:
        # Tell randomizer to wait 5 seconds when starting up
        - name: DELAY_STARTUP
          value: "5"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
        readinessProbe:
          # We are checking for a file created by our app when its ready
          exec:
            command: [ "stat", "/tmp/randomizer-ready" ]
        ports:
        - containerPort: 8080
          protocol: TCP
      # Allow scheduling also on the master nodes, which typically is tainted
      # for no-schedule
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
