apiVersion: batch/v1
kind: CronJob
metadata:
  name: randomizer
spec:
  # Every three minutes
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      # Template for the job to generate
      template:
        spec:
          containers:
          - image: akaliutau/randomizer:1.0
            name: randomizer
            command:
            - java
            # Use / as classpath to pick up the class file
            # Class running batch job
            - RandomRunner
            # 1. Arg: File to store data (on a PV)
            - /tmp/logs/random.log
            # 2. How many iterations
            - "10000"
            # Mount directory to where to write the results
            volumeMounts:
            - mountPath: /tmp/logs
              name: log-volume
          restartPolicy: OnFailure
          volumes:
          - name: log-volume
            persistentVolumeClaim:
              claimName: randomizer-log
