# A recreate (or fixed) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer
spec:
  replicas: 3
  strategy:
    # Kill first all old Pods, then start the new version
    type: Recreate
  selector:
    matchLabels:
      app: randomizer
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
      - image: akaliutau/randomizer:1.0
        name: randomizer
        env:
        - name: PATTERN
          value: Declarative Deployment
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
        readinessProbe:
          exec:
            command: [ "stat", "/tmp/randomizer-ready" ]
