apiVersion: v1
kind: Pod
metadata:
  name: randomizer
  labels:
    app: randomizer
spec:
  containers:
  - image: akaliutau/randomizer:1.0
    name: randomizer
    env:
    - name: PATTERN
      value: Self Awareness
    # The Downward API allows access to fields
    # in this declaration
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    volumeMounts:
    - name: pod-info
      mountPath: /pod-info
    ports:
    - containerPort: 8080
      protocol: TCP
  volumes:
  - name: pod-info
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels
      - path: annotations
        fieldRef:
          fieldPath: metadata.annotations
