# Resource limits
apiVersion: v1
kind: Pod
metadata:
  name: randomizer
  labels:
    app: randomizer
spec:
  containers:
  - image: akaliutau/randomizer:1.0
    name: randomizer
    env:
    - name: PATTERN
      valueFrom:
        # First hard requirement for a config map to exist.
        configMapKeyRef:
          name: randomizer-config
          key: pattern
    # Enabling logging into the mounted volume
    - name: LOG_FILE
      value: /tmp/logs/random.log
    volumeMounts:
      - mountPath: /tmp/logs
        name: log-volume
  volumes:
    - name: log-volume
      # Second hard requirement is that the specified persitent volume claim
      # exists and is bound.
      persistentVolumeClaim:
        claimName: randomizer-log
