apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomizer
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: randomizer
            port:
              number: 8080
      - path: /status
        pathType: Prefix
        backend:
          service:
            name: service-status
            port:
              number: 8080

