# DeploymentConfig for starting up the randomizer-runtime
apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomizer
  template:
    metadata:
      labels:
        app: randomizer
    spec:
      containers:
      - image: registry:80/k8stest/randomizer
        imagePullPolicy: Always
        name: randomizer
        ports:
        - containerPort: 8080
          protocol: TCP
---
# A service for exposing our random generator
apiVersion: v1
kind: Service
metadata:
  name: randomizer
spec:
  selector:
    app: randomizer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
# The ingress for accessing the service from externally.
# Use `kubectl get ingress` to find out the URL
# On Minishift best try it with:
# curl -s http://randomizer.$(minikube ip).nip.io/
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: randomizer
spec:
  backend:
    serviceName: randomizer
    servicePort: 8080
