# DeploymentConfig for starting up the randomizer
apiVersion: v1
kind: Pod
metadata:
  name: randomizer
  labels:
    app: randomizer
spec:
  containers:
  # ------------------------------------------------
  # Main application
  - image: akaliutau/randomizer:1.0
    name: main
    env:
    # URL to the port our ambassador is listening.
    - name: LOG_URL
      value: http://localhost:9009
    ports:
    # Application running on port 8080
    - containerPort: 8080
      protocol: TCP
  # ------------------------------------------------
  # Ambassador used for logging out
  - image: k8stest/randomizer-log-ambassador
    name: ambassador
