apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: main
    image: nginx
    volumeMounts:
    - name: shared
      mountPath: /usr/share/nginx/html
  - name: sidecar
    image: debian
    volumeMounts:
    - name: shared
      mountPath: /shared
    command: ["/bin/sh"]
    args: ["-c", "echo Output from the sidecar container > /shared/index.html && sleep 60"]
  restartPolicy: Never