apiVersion: v1
kind: Pod
metadata:
  name: termination-pod
spec:
  containers:
  - name: termination
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 20 && echo Done sleeping > /termination-log"]
    terminationMessagePath: "/termination-log"
  restartPolicy: Never